ajedrez/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
# from normativa import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path CKEDITOR
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # Path CORE
    path("", include('core.urls', namespace='torneo')),
    # Path CONTACTO
    path("contacto/", include('contacto.urls', namespace='contacto')),
    # Path NORMATIVA
    path("normativas/", include('normativa.urls', namespace='normativa')),
    # Path BLOG
    path('blog/', include('blog.urls', namespace='blog')),
    # Path CIRCUITO DIPUTACION
    path('circuito-diputacion/', include('circuitos.urls', namespace="circuitos")),
    # Path ESCUELAS Y CLUBES
    path('clubes-de-ajedrez/', include('escuelas.urls', namespace="escuelas")),
    # Path PAGE
    path("pagina/", include("page.urls", namespace="pagina")),
]

admin.site.site_header = 'Administración AjedrezMálaga'

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("search/", views.post_search, name="post_search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "categorias/<int:category_id>/<slug:category_name>/",
        views.post_list,
        name="category",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post-detail",
    ),
]

circuitos/urls.py
from django.urls import path
from . import views

app_name = 'circuitos'

urlpatterns = [
    path(
        '',
        views.circuito_torneos_list,
        {'tipo_torneo': 'nuevos'},
        name='new_tournaments',
    ),
    path("search/", views.circuito_search, name="circuito_search"),
    path(
        'todos-los-torneos/',
        views.circuito_torneos_list,
        {'all_tournaments': True, 'tipo_torneo': 'todos'},
        name='all_tournaments',
    ),
    path(
        'torneos-en-curso/',
        views.circuito_torneos_list,
        {'in_progress': True, 'tipo_torneo': 'en curso'},
        name='tournaments_in_progress',
    ),
    path(
        'torneos-finalizados/',
        views.circuito_torneos_list,
        {'finished': True, 'tipo_torneo': 'finalizados'},
        name='finished_tournaments',
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.circuito_torneo_detail,
        name='circuito-detail',
    ),
    # Path torneos año en curso
    path(
        'historico-torneos/',
        views.historico_torneos_diputacion,
        name='historico-torneos-diputacion',
    ),
    # Path torneos año y mes
    path(
        'historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos_diputacion,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos_diputacion,
        name='todo-historico',
    ),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Path del core
    path('', views.home, name="inicio"),
    path('torneos/', views.agenda, name='agenda'),
    path(
        'torneos/<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.torneo_detail,
        name='torneo-detail',
    ),
    # Path torneos año en curso
    path('torneos/historico-torneos/', views.historico_torneos, name='historico-torneos'),
    # Path torneos año y mes
    path(
        'torneos/historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'torneos/historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos,
        name='todo-historico'
    ),
]

circuitos/forms.py
from django import forms
from .models import RegistrationTournamentDiputacion


class RegistrationTournamentDiputacionForm(forms.ModelForm):
    class Meta:
        model = RegistrationTournamentDiputacion
        fields = [
            "name",
            "surnames",
            "mail",
            "population",
            "zip_code",
            "date_birth",
            "phone",
            "privacy_policy",
            "tournament_title",
            "status",
            "category",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "surnames": forms.TextInput(attrs={"class": "form-control"}),
            "population": forms.TextInput(attrs={"class": "form-control"}),
            "zip_code": forms.TextInput(attrs={"class": "form-control"}),
            "mail": forms.EmailInput(attrs={"class": "form-control"}),
            "privacy_policy": forms.CheckboxInput(
                attrs={"class": "form-check-label", "required": True}
            ),
            "phone": forms.TextInput(
                attrs={
                    "type": "tel",
                    "required": True,
                    "pattern": "[0-9]{3}[0-9]{3}[0-9]{3}",
                    "placeholder": "666555333",
                    "class": "form-control",
                }
            ),
            "date_birth": forms.TextInput(
                attrs={
                    "type": "date",
                    "required": True,
                    "class": "form-control",
                }
            ),
        }


class LowInTournamentDiputacionForm(forms.Form):
    name = forms.CharField(max_length=100)
    surnames = forms.CharField(max_length=150)
    mail = forms.EmailField()
    privacy_policy = forms.BooleanField()

    name.widget.attrs.update({"class": "form-control"})
    surnames.widget.attrs.update({"class": "form-control"})
    mail.widget.attrs.update({"class": "form-control"})
    privacy_policy.widget.attrs.update({"class": "form-check-label", "required": True})


class SearchForm(forms.Form):
    query = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'type': 'search',
                'placeholder': 'Buscar...',
                'aria-label': 'Buscar en el listado de torneos del circuito de la diputacion',
                'class': 'form-control me-2',
            }
        ),
    )

circuitos/views.py
import requests
import datetime
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mass_mail
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import TorneoDiputacion, RegistrationTournamentDiputacion
from .forms import RegistrationTournamentDiputacionForm, LowInTournamentDiputacionForm, SearchForm
from .tasks import register_created, low_created


def circuito_torneos_list(request, tipo_torneo=None, all_tournaments=None, in_progress=None, finished=None):

    form_search = SearchForm()
    current_month = timezone.now().strftime("%m")
    torneos_mes_actual = TorneoDiputacion.objects.filter(start__month=int(current_month))

    # utilizamos date para comprobar solo fechas con el formato Y-m-d
    # Refe:https://docs.djangoproject.com/en/3.2/ref/models/querysets/#date

    # Por defecto se muestran los torneos nuevos
    object_list = TorneoDiputacion.objects.filter(
            start__date__gt=timezone.now().strftime("%Y-%m-%d")
    )

    if all_tournaments:
        print(all_tournaments, "Solicita todos los torneos")
        object_list = TorneoDiputacion.objects.all()

    if in_progress:
        print(in_progress, "Solicita torneos en progreso")
        object_list = TorneoDiputacion.objects.filter(
            start__date__lte=timezone.now().strftime("%Y-%m-%d"),
            finish__date__gte=timezone.now().strftime("%Y-%m-%d"),
        )

    if finished:
        print(finished, "Solicita torneos finalizados")
        object_list = TorneoDiputacion.objects.filter(
            finish__date__lt=timezone.now().strftime("%Y-%m-%d")
        )

    paginator = Paginator(object_list, 10)  # torneos(objects) in each page
    page = request.GET.get("page")

    try:
        torneos = paginator.page(page)  # todos los objetos de una página

    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        torneos = paginator.page(1)

    except EmptyPage:
        # if pages is out of range deliver las page of results
        torneos = paginator.page(paginator.num_pages)

    return render(
        request,
        "circuitos/circuitos_list.html",
        {
            'torneos': torneos,
            'form': form_search,
            'tipo_torneo': tipo_torneo,
            'torneos_mes_actual': torneos_mes_actual
        }
    )


def circuito_torneo_detail(request, year, month, day, torneo):
    torneo = get_object_or_404(
        TorneoDiputacion, slug=torneo, publish__year=year, publish__month=month, publish__day=day
    )
    allow_registration = False
    submitted_form = False

    if not torneo.quantity and not torneo.registre:  # organiza delegación y no aforo
        allow_registration = False
    elif timezone.now().strftime("%Y-%m-%d") >= torneo.end_registration.strftime(
        "%Y-%m-%d"
    ):  # para todos organize quien organize
        allow_registration = False
    elif torneo.quantity and not torneo.registre:  # organiza delegación y hay aforo
        allow_registration = True
    elif not torneo.quantity and torneo.registre:
        # organiza 3 parte y fecha actual < fecha fin registro
        allow_registration = True

    form = RegistrationTournamentDiputacionForm()
    low_form = LowInTournamentDiputacionForm()

    if request.method == "POST":
        if "low" in request.POST:
            low_form = LowInTournamentDiputacionForm(request.POST)
            form = RegistrationTournamentDiputacionForm()

            if low_form.is_valid():
                """reCAPTCHA validation"""
                recaptcha_response = request.POST.get("g-recaptcha-response")
                data = {
                    "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                    "response": recaptcha_response,
                }
                r = requests.post(
                    "https://www.google.com/recaptcha/api/siteverify", data=data
                )
                result = r.json()

                print(result)

                """ if reCAPTCHA returns True """
                if result["success"]:
                    # diccionario datos limpios del formulario de baja
                    cd = low_form.cleaned_data
                    try:
                        registration = RegistrationTournamentDiputacion.objects.get(
                            name=cd["name"],
                            surnames=cd["surnames"],
                            mail=cd["mail"],
                            tournament_title=request.POST.get("tournament_title"),
                        )
                        registration.delete()
                        messages.info(request, "Baja realizada con éxito.")
                        torneo.quantity = torneo.quantity + 1  # update
                        torneo.save()
                        
                        low_created.delay(cd, torneo.title)
                        # message1 = (
                        #     "Baja en torneo",
                        #     f"Enhorabuena {cd['name']} te has dado de baja en el torneo {torneo.title}",
                        #     "info@ajedrezmalaga.org",
                        #     [f"{cd['mail']}"],
                        # )
                        # message2 = (
                        #     "Baja en torneo",
                        #     f"{cd['name']} {cd['surnames']} se ha dado de baja en el torneo {torneo.title}",
                        #     "info@ajedrezmalaga.org",
                        #     ["admin@ajedrezmalaga.org"],
                        # )

                        # send_mass_mail((message1, message2), fail_silently=False)
                        low_form = LowInTournamentDiputacionForm()
                    except ObjectDoesNotExist:
                        messages.error(request, "El usuario no está registrado.")

        elif not "low" in request.POST:
            print(request.POST)
            form = RegistrationTournamentDiputacionForm(request.POST)
            low_form = LowInTournamentDiputacionForm()

            if form.is_valid():
                """reCAPTCHA validation"""
                recaptcha_response = request.POST.get("g-recaptcha-response")
                data = {
                    "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                    "response": recaptcha_response,
                }
                r = requests.post(
                    "https://www.google.com/recaptcha/api/siteverify", data=data
                )
                result = r.json()

                print(result)

                """ if reCAPTCHA returns True """
                if result["success"]:
                    print("FORMULARIO ENVIADO CON EXITO")
                    new_tournamentregistration = form.save(commit=False)
                    new_tournamentregistration.tournament = torneo
                    # new_tournamentregistration.status = request.POST.get('status')
                    new_tournamentregistration.save()

                    torneo.quantity = torneo.quantity - 1  # update
                    torneo.save()
                    # print('Torneo despues de grabar', torneo.quantity)

                    # envio correo electronico a la delegación y al registrado
                    # para ello utilizaremos send_mass_mail()
                    # https://docs.djangoproject.com/en/3.2/topics/email/#send-mass-mail
                    cd = form.cleaned_data

                    register_created.delay(cd, torneo.title)
                    # message1 = (
                    #     "Inscripción en torneo",
                    #     f"Enhorabuena {cd['name']} te has registrado en el torneo {torneo.title}",
                    #     "info@ajedrezmalaga.org",
                    #     [f"{cd['mail']}"],
                    # )
                    # message2 = (
                    #     "Inscripción en torneo",
                    #     f"{cd['name']} {cd['surnames']} se ha registrado en el torneo {torneo.title}",
                    #     "info@ajedrezmalaga.org",
                    #     ["admin@ajedrezmalaga.org"],
                    # )

                    # send_mass_mail((message1, message2), fail_silently=False)

                    submitted_form = True
                    form = RegistrationTournamentDiputacionForm()  # borrar campos crear form nuevo

    # else:
    #     form = RegistrationTournamentDiputacionForm()
    #     low_form = LowInTournamentDiputacionForm()

    return render(
        request,
        "circuitos/circuito_detail.html",
        {
            "torneo": torneo,
            "allow_registration": allow_registration,
            "recaptcha_site_key": settings.GOOGLE_RECAPTCHA_SITE_KEY,
            "form": form,
            "submitted_form": submitted_form,
            "low_form": low_form,
        },
    )


def circuito_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # Búsqueda
            results = set(
                TorneoDiputacion.objects.filter(
                    Q(title__icontains=query)
                    | Q(location__icontains=query)
                    | Q(body__icontains=query)
                    | Q(province__icontains=query)
                )
            )
            print(results)

    return render(
        request,
        "circuitos/search.html",
        {"query": query, "form": form, "results": results},
    )


def historico_torneos_diputacion(request, year=None, month=None, all_tournaments=None):
    '''Vamos a obtener los torneos de los dos años anteriores al año en curso, los
    torneos del año en curso y los torneos de un año y un mes'''

circuitos/templates/circuitos/circuitos_list.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Cicuito | Diputación{% endblock title %}

{% block css %}<link rel="stylesheet" href="{% static 'core/fullcalendar/lib/main.css' %}" />{% endblock css %}
{% block csspage %}<link rel="stylesheet" href="{% static 'circuitos/css/circuitos.css' %}"/>{% endblock csspage %}

{% block section %}<section>
    <div class="container col-xxl-8 px-4 pb-5 pt-3">
      <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">
          <img
            src="{% static 'circuitos/img/circuito_ajedrez.webp' %}"
            class="d-block mx-lg-auto img-fluid rounded"
            alt="Circuito Diputación Málaga"
            width="700"
            height="500"
            loading="lazy"
          />
        </div>
        <div class="col-lg-6">
          <h1 class="display-5 fw-bold lh-1 mb-3">Cicuitos de la Diputación</h1>
          <p class="lead">
            Con el buen tiempo llega el Circuito Provincial de la Diputación de Málaga, y nada mejor que disfrutarlo
            jugando al ajedrez y recorriendo los numerosos pueblos malagueños adheridos al Circuito.
          </p>
          <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          </div>
        </div>
      </div>
    </div>

    <!-- Calendar -->
    <div class="container">
      <div class="row">
        <div id='calendar'></div>
      </div>
    </div>
    <br><br><br>

    <div class="b-example-divider"></div>
  </section>{% endblock section %}

{% block breadcrumb %}<div class="container my-4">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'torneo:inicio' %}">Inicio</a></li>
        <li class="breadcrumb-item active" aria-current="page">Circuito Diputación</li>
      </ol>
    </nav>
    <!-- End breadcrumb -->
  </div>{% endblock breadcrumb %}

{% block main %}<main class="container my-5">
    <div class="tournaments-and-sidebar">
      <div class="tournaments-of-diputacion">
        <div class="card">
          <div class="card-body">
            <nav class="navbar navbar-light bg-light mb-4">
              <div class="container-fluid">
                <!-- Buscador -->
                <form action="{% url 'circuitos:circuito_search' %}" method="GET" class="d-flex">
                  {{ form.query }}
                  <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <!-- fin buscador -->
                <ul class="nav justify-content-end">
                  <li class="nav-item dropdown">
                    <a
                      class="nav-link dropdown-toggle"
                      data-bs-toggle="dropdown"
                      href="#"
                      role="button"
                      aria-expanded="false"
                    >Seleccionar</a
                    >
                    <ul class="dropdown-menu">
                      <li>
                        <a class="dropdown-item"
                           href="{% url 'circuitos:new_tournaments' %}">Nuevos
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-item"
                           href="{% url 'circuitos:tournaments_in_progress' %}">En curso
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-item"
                           href="{% url 'circuitos:finished_tournaments' %}">Finalizados
                        </a>
                      </li>
                      <li>
                        <hr class="dropdown-divider"/>
                      </li>
                      <li><a class="dropdown-item" href="{% url 'circuitos:all_tournaments' %}">Todos</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>
            <h5 class="card-title text-center mb-3">Torneos de la diputación {% if tipo_torneo %}({{ tipo_torneo }}){% endif %}</h5>
            <div class="table-responsive">
              <table class="table table-striped">
                <thead class="table-dark-blue">
                <tr>
                  <th scope="col">Inicio</th>
                  <th scope="col">Final</th>
                  <th scope="col">Torneo</th>
                  <th scope="col">Localidad</th>
                  <th scope="col">Provincia</th>
                </tr>
                </thead>
                <tbody>
                {% for torneo in torneos %}
                  <tr>
                    <th scope="row">{{ torneo.start|date:"SHORT_DATE_FORMAT" }}</th>
                    <td>{{ torneo.finish|date:"SHORT_DATE_FORMAT" }}</td>
                    <td><a href="{{ torneo.get_absolute_url }}">{{ torneo.title }}</a></td>
                    <td>{{ torneo.location }}</td>
                    <td>{{ torneo.province }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- end table-responsive -->
          </div>
          <!-- end card-body -->
        </div>
        <!-- end card -->
        <!-- Pagination -->
       {% if torneos %}{% include "circuitos/pagination.html" with page=torneos %}{% endif %}
        <!-- end pagination -->
      </div>
      <!-- end tournaments-of-diputacion -->

      <div class="sidebar-of-advertising">
        <div class="single-module">
          <div class="module">
            <a href="#">
              <img src="{% static 'blog/img/promo-1.jpg' %}" alt="imagen-patrocinador">
            </a>
          </div>
          <div class="interlude">
            <a href="#"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis voluptates.</p></a>
          </div>
        </div>
        <div class="single-module">
          <div class="module">
            <a href="#">
              <img src="{% static 'blog/img/promo-2.png' %}" alt="imagen-patrocinador">
            </a>
          </div>
          <div class="interlude">
            <a href="#"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis voluptates.</p></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end tournaments-and-sidebar -->
  </main>{% endblock main %}

{% block javascript %}<script type="text/javascript" src="{% static 'core/fullcalendar/lib/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/fullcalendar/lib/locales/es.js' %}"></script>{% endblock javascript %}

{% block extra %}<!-- Javascript para Calendar -->
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          themeSystem: 'standard',  // default
          headerToolbar: { center: 'dayGridMonth,timeGridWeek' }, // buttons for switching between views
          initialView: 'dayGridMonth',  // default
          contentHeight: 450,

          events: [
           {% for torneo in torneos_mes_actual %}
             {
               title: "{{ torneo.title }}",
               start: '{{ torneo.start | date:"Y-m-d" }}',
               url: '{{ torneo.get_absolute_url }}',
             },
           {% endfor %}
          ]
        });
        calendar.setOption('locale', 'es');
        calendar.render();
      });
    </script>{% endblock extra %}
</body>
</html>

circuitos/templates/circuitos/pagination.html
<!-- Pagination -->
<nav class="my-4" aria-label="Page navigation example">
  <ul class="pagination justify-content-end">
  {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
    </li>
  {% endif %}

  {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}

  {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Siguiente</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Siguiente</a>
    </li>
  {% endif %}
  </ul>
</nav>

circuitos/templates/circuitos/search.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Búsqueda Circuito Diputación | Ajedrez Málaga{% endblock title %}

{% block css %}<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">{% endblock css %}
{% block csspage %}<link rel="stylesheet" href="{% static 'circuitos/css/circuitos.css' %}" />{% endblock csspage %}

{% block breadcrumb %}<!-- Breadcrumb -->
<div class="container my-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'torneo:inicio' %}">Inicio</a></li>
      <li class="breadcrumb-item"><a href="{% url 'circuitos:new_tournaments' %}">Circuito Diputación</a></li>
      <li class="breadcrumb-item active" aria-current="page">Búsqueda</li>
    </ol>
  </nav>
</div>{% endblock breadcrumb %}

{% block section %}
<section class="container px-4 mb-5">
  <h1 class="display-5 fw-bold text-blue-gradient text-center py-5">
    Resultados de la búsqueda
  </h1>
  <div class="row g-5">
    <div class="col">
      <div class="list-group">
      {% for torneo in results %}
      <a href="{{ torneo.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-primary">{{ torneo.title }}</a>
      {% empty %}
        <h3>¡Vaya!, parece que no hay resultados.</h3>
      {% endfor %}
      </div>
    </div>  <!-- fin col -->
  </div>  <!-- fin row -->
  {% if not results %}
  <div class="row mt-3">
    <!-- Búsqueda -->
    <form action="{% url 'circuitos:circuito_search' %}" method="GET" class="d-flex">
      {{ form.query }}
      <button class="btn btn-outline-success" type="submit">Buscar</button>
    </form>
  </div>
  {% endif %}
</section>{% endblock section %}