ajedrez/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
# from normativa import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path CKEDITOR
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # Path CORE
    path("", include('core.urls', namespace='torneo')),
    # Path CONTACTO
    path("contacto/", include('contacto.urls', namespace='contacto')),
    # Path NORMATIVA
    path("normativas/", include('normativa.urls', namespace='normativa')),
    # Path BLOG
    path('blog/', include('blog.urls', namespace='blog')),
    # Path CIRCUITO DIPUTACION
    path('circuito-diputacion/', include('circuitos.urls', namespace="circuitos")),
    # Path ESCUELAS Y CLUBES
    path('clubes-de-ajedrez/', include('escuelas.urls', namespace="escuelas")),
    # Path PAGE
    path("pagina/", include("page.urls", namespace="pagina")),
]

admin.site.site_header = 'Administración AjedrezMálaga'

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("search/", views.post_search, name="post_search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "categorias/<int:category_id>/<slug:category_name>/",
        views.post_list,
        name="category",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post-detail",
    ),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Path del core
    path('', views.home, name="inicio"),
    path('torneos/', views.agenda, name='agenda'),
    path(
        'torneos/<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.torneo_detail,
        name='torneo-detail',
    ),
    # Path torneos año en curso
    path('torneos/historico-torneos/', views.historico_torneos, name='historico-torneos'),
    # Path torneos año y mes
    path(
        'torneos/historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'torneos/historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos,
        name='todo-historico'
    ),
]

normativa/urls.py
from django.urls import path
from . import views

app_name = "normativa"

urlpatterns = [
    # Path todas las circulares año en curso
    path("", views.circular, name="circulares"),
    # Path Buscar, importante que vaya en primer lugar, sino no funcionará
    path("search/", views.circular_search, name="circular_search"),
    # Path todas las circulares
    path("<slug:todas_circulares>/", views.circular, name="todas-circulares"),
    # Path circulares año y mes
    path(
        "circulares/<int:year>/<int:month>/",
        views.circular,
        name="circulares-year-month",
    ),
]

normativa/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from cloudinary_storage.storage import RawMediaCloudinaryStorage


class Circular(models.Model):
    title = models.CharField('título circular', max_length=200)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        verbose_name='autor',
        on_delete=models.CASCADE,
        related_name='get_circulares',
    )

    file_pdf = models.FileField('circulares', upload_to='pdf/%Y/%m/%d/', storage=RawMediaCloudinaryStorage())
    publish = models.DateTimeField('fecha de la circular', default=timezone.now)
    created = models.DateTimeField('fecha de creación', auto_now_add=True)
    updated = models.DateTimeField('fecha de edición', auto_now=True)
    search_date = models.CharField(blank=True, max_length=200)  # desde cero no hara falta blank=True

    class Meta:
        ordering = ['-publish']
        verbose_name_plural = 'circulares'

    def save(self, *args, **kwargs):
        self.search_date = self.publish.strftime("%d %B %Y")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

normativa/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={
                "type": "search",
                "placeholder": "Buscar...",
                "aria-label": "Search",
                "class": "form-control me-2",
            }
        ),
    )

normativa/views.py
import datetime
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q
from .models import Circular
from .forms import SearchForm


def circular(request, year=None, month=None, todas_circulares=None):
    ''''''

    qs = False
    formatted_date = ''
    before_last_year = str(int(timezone.now().strftime("%Y")) - 2)
    last_year = str(int(timezone.now().strftime("%Y")) - 1)
    current_year = timezone.now().strftime("%Y")
    form_search = SearchForm()

    # todos las circulares año curso
    object_list = Circular.objects.filter(publish__year=current_year)

    if todas_circulares:
        object_list = Circular.objects.all()

    if year and month:
        object_list = Circular.objects.filter(
            publish__year=int(year), publish__month=int(month)
        )
        qs = True
        formatted_date = datetime.datetime(year, month, 17).strftime("%B %Y")

    # object_list = Circular.objects.all()

    paginator = Paginator(object_list, 10)  # circulares(objects) in each page
    page = request.GET.get("page")
    try:
        circulares = paginator.page(page)  # todos los objetos de una página

    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        circulares = paginator.page(1)

    except EmptyPage:
        # if pages is out of range deliver las page of results
        circulares = paginator.page(paginator.num_pages)

    return render(
        request,
        "normativa/circular_list.html",
        {
            "circulares": circulares,
            "page": page,
            'current_year': current_year,
            'last_year': last_year,
            'before_last_year': before_last_year,
            'qs': qs,
            'formatted_date': formatted_date,
            'todas_las_circulares': todas_circulares,
            'form': form_search
        },
    )


def circular_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # Búsqueda
            results = set(
                Circular.objects.filter(
                    Q(title__icontains=query) | Q(search_date__icontains=query)
                )
            )
            print(results)

    return render(
        request, "normativa/search.html", {"query": query, "form": form, "results": results}
    )


# def historico_circulares(request, year=None, month=None, todas_circulares=None):
#     '''Vamos a obtener las circulares de los dos años anteriores al año en curso'''

#     year_month_circulares = None
#     get_all_circulares = False
#     qs = False
#     formatted_date = ''
#     before_last_year = str(int(timezone.now().strftime("%Y")) - 2)
#     last_year = str(int(timezone.now().strftime("%Y")) - 1)
#     current_year = timezone.now().strftime("%Y")

#     if todas_circulares:
#         get_all_circulares = Circular.objects.all()

#     if year and month:
#         year_month_circulares = Circular.objects.filter(
#             start__year=int(year), start__month=int(month)
#         )
#         qs = True
#         formatted_date = datetime.datetime(year, month, 17).strftime("%B %Y")

#     # todos las circulares cuya fecha de comienzo es el mes actual del año curso
#     current_year_circulares = Circular.objects.filter(start__year=current_year)

#     return render(
#         request,
#         "core/circular_list.html",
#         {
#             "current_year_circulares": current_year_circulares,
#             'current_year': current_year,
#             'last_year': last_year,
#             'before_last_year': before_last_year,
#             'year_month_circulares': year_month_circulares,
#             'qs': qs,
#             'formatted_date': formatted_date,
#             'get_all_circulares': get_all_circulares,
#         },
#     )

normativa/templates/normativa/search.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Búsqueda Normativas | Ajedrez Málaga{% endblock title %}

{% block css %}<link rel="stylesheet" href="{% static 'core/css/pdfjs-viewer.min.css' %}" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">{% endblock css %}

{% block csspage %}<link rel="stylesheet" href="{% static 'normativa/css/circular.css' %}" />{% endblock csspage %}

{% block breadcrumb %}<!-- Breadcrumb -->
<div class="container my-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'torneo:inicio' %}">Inicio</a></li>
      <li class="breadcrumb-item"><a href="{% url 'normativa:circulares' %}">Circulares</a></li>
      <li class="breadcrumb-item active" aria-current="page">Búsqueda</li>
    </ol>
  </nav>
</div>{% endblock breadcrumb %}

{% block section %}<!-- Modal Pdf -->
<div class="modal fade" id="pdfModal" tabindex="-1" aria-labelledby="pdfModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="pdfModalLabel">{{ circular.title }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- <iframe src="" frameborder="0" width="100%" height="400px"></iframe> -->
        <div class="pdftoolbar text-center row m-0 p-0">
          <div class="col-12 col-lg-6 my-1">
            <button class="btn btn-secondary btn-sm" onclick="pdfViewer.setZoom('out')"><span
                class="material-icons">zoom_out</span></button>
            <span class="zoomval">100%</span>
            <button class="btn btn-secondary btn-sm" onclick="pdfViewer.setZoom('in')"><span
                class="material-icons">zoom_in</span></button>
            <button class="btn btn-secondary btn-sm ms-3" onclick="pdfViewer.setZoom('width')"><span
                class="material-icons">swap_horiz</span></button>
            <button class="btn btn-secondary btn-sm" onclick="pdfViewer.setZoom('height')"><span
                class="material-icons">swap_vert</span></button>
            <button class="btn btn-secondary btn-sm" onclick="pdfViewer.setZoom('fit')"><span
                class="material-icons">fit_screen</span></button>
          </div>
        </div>
        <div class="pdfjs-viewer"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div><!-- fin modal -->

<section class="container px-4 mb-5">
  <h1 class="display-5 fw-bold text-blue-gradient text-center py-5">
    Resultados de la búsqueda
  </h1>
  <div class="row g-5">
    <div class="col">
      <div class="grid-fit">
        {% for circular in results %}
        <div class="item-grid border border-1">
          <div class="img-wrapper"><img src="{% static 'core/img/pdf.webp' %}" alt="img placeholder" /></div>
          <div class="item-info">
            <div class="title"><h5>{{ circular.title }}</h5></div>
            <div class="item-name"><p>{{ circular.publish|date:"j F Y" }}</p></div>
            <div class="description">
              <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#pdfModal"
                data-bs-whatever="{{ circular.file_pdf.url }}" data-bs-title="{{ circular.title }}">
                Leer circular
              </button>
            </div>
          </div>
        </div>
        {% empty %}
        <h3>¡Vaya!, parece que no hay resultados.</h3>
        {% endfor %}
      </div>  <!-- end grid-fit -->
      <!-- {% if circulares %}{% include "core/pagination.html" with page=circulares %}{% endif %} -->
    </div>  <!-- fin col -->
  </div>  <!-- fin row -->
  {% if not results %}
  <div class="row mt-3">
    <!-- Búsqueda -->
    <form action="{% url 'normativa:circular_search' %}" method="GET" class="d-flex">
      {{ form.query }}
      <button class="btn btn-outline-success" type="submit">Buscar</button>
    </form>
  </div>
  {% endif %}
</section>{% endblock section %}

{% block javascript %}<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.12.313/pdf.min.js"></script>
<script>
  var pdfjsLib = window['pdfjs-dist/build/pdf'];
  pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.12.313/pdf.worker.min.js';
</script>
<script src="{% static 'core/js/pdfjs-viewer.min.js' %}"></script>
<script>
  var pdfModal = document.getElementById('pdfModal')
  let pdfViewer = new PDFjsViewer($('.pdfjs-viewer'), {
    onZoomChange: function (zoom) {
      zoom = parseInt(zoom * 10000) / 100;
      $('.zoomval').text(zoom + '%');
    },
    onActivePageChanged: function (page, pageno) {
      $('.pageno').text(pageno + '/' + this.getPageCount());
    }
  });
  pdfModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget
    // Extract info from data-bs-* attributes
    var recipient = button.getAttribute('data-bs-whatever')
    var title = button.getAttribute('data-bs-title')
    // If necessary, you could initiate an AJAX request here
    // and then do the updating in a callback.
    //
    // Update the modal's content.
    var modalTitle = pdfModal.querySelector('.modal-title')
    // var modalBodyIframe = pdfModal.querySelector('.modal-body iframe')

    modalTitle.textContent = title
    // modalBodyIframe.src = recipient
    pdfViewer.loadDocument(recipient).then(function () {
      pdfViewer.setZoom('fit');
    });
  })
</script>{% endblock javascript %}