ajedrez/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
# from normativa import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path CKEDITOR
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # Path CORE
    path("", include('core.urls', namespace='torneo')),
    # Path CONTACTO
    path("contacto/", include('contacto.urls', namespace='contacto')),
    # Path NORMATIVA
    path("normativas/", include('normativa.urls', namespace='normativa')),
    # Path BLOG
    path('blog/', include('blog.urls', namespace='blog')),
    # Path CIRCUITO DIPUTACION
    path('circuito-diputacion/', include('circuitos.urls', namespace="circuitos")),
    # Path ESCUELAS Y CLUBES
    path('clubes-de-ajedrez/', include('escuelas.urls', namespace="escuelas")),
    # Path PAGE
    path("pagina/", include("page.urls", namespace="pagina")),
]

admin.site.site_header = 'Administración AjedrezMálaga'

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("search/", views.post_search, name="post_search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "categorias/<int:category_id>/<slug:category_name>/",
        views.post_list,
        name="category",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post-detail",
    ),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Path del core
    path('', views.home, name="inicio"),
    path('torneos/', views.agenda, name='agenda'),
    path(
        'torneos/<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.torneo_detail,
        name='torneo-detail',
    ),
    # Path torneos año en curso
    path('torneos/historico-torneos/', views.historico_torneos, name='historico-torneos'),
    # Path torneos año y mes
    path(
        'torneos/historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'torneos/historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos,
        name='todo-historico'
    ),
]

blog/models.py
import requests
import json
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from taggit.managers import TaggableManager

url = "https://onesignal.com/api/v1/notifications"


# Modelo CATEGORIA
class Category(models.Model):
    name = models.CharField("nombre", max_length=100)
    created = models.DateTimeField("fecha de creación", auto_now_add=True)
    updated = models.DateTimeField("fecha de edición", auto_now=True)

    class Meta:
        ordering = ["-created"]
        verbose_name = "categoría"
        verbose_name_plural = "categorías"

    def __str__(self):
        return self.name


# Manager Personalizado
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


# Modelo POST
class Post(models.Model):
    STATUS_CHOICES = (("draft", "Borrador"), ("published", "Publicado"))

    title = models.CharField("titulo", max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User,
        verbose_name="autor",
        on_delete=models.CASCADE,
        related_name="blog_posts",
    )

    image = models.ImageField("imagen", upload_to="blog", blank=True, null=True)
    body = RichTextUploadingField("contenido")
    categories = models.ManyToManyField(
        Category,
        verbose_name="categorías",
        related_name="get_posts",
        blank=True,
    )

    publish = models.DateTimeField("fecha de publicación", default=timezone.now)
    created = models.DateTimeField("fecha de creación", auto_now_add=True)
    updated = models.DateTimeField("fecha de modificación", auto_now=True)
    search_date = models.CharField(
        blank=True, max_length=200
    )  # desde cero no hara falta blank=True
    status = models.CharField(
        "estado", max_length=10, choices=STATUS_CHOICES, default="draft"
    )

    objects = models.Manager()  # el manager por defecto
    published = PublishedManager()  # nuestro manager personalizado.
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]

    def get_absolute_url(self):
        return reverse(
            "blog:post-detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

    def save(self, *args, **kwargs):
        self.search_date = self.publish.strftime("%d %B %Y")
        super().save(*args, **kwargs)
        payload = {
            "app_id": "a916b202-a622-4aa2-8556-b4dcf3bc60ef",
            # "included_segments": ["Subscribed Users"],
            "excluded_segments": ["Inactive Users"],
            "filters": [
                # segment e include_segments son ignorados y por tanto no se ponen cuando se
                # utiliza filters.
                {
                    "field": "tag",
                    "key": "articulos_del_blog",
                    "relation": "=",
                    "value": "1",
                }
            ],
            # "delayed_option": "last-active",
            "delayed_option": "immediate",
            "headings": {
                "en": "The notification's title.",
                "es": self.title,
            },
            "contents": {
                "en": "New Article in our blog.",
                "es": "Nuevo artículo creado, visita nuestro blog.",
            },
            "web_url": f"http://127.0.0.1:8000{self.get_absolute_url()}",
            "chrome_web_image": self.image.url,
            "web_buttons": [
                {
                    "id": "read-more-button",
                    "text": "Leer artículo",
                    "icon": "http://i.imgur.com/MIxJp1L.png",
                    "url": f"http://127.0.0.1:8000{self.get_absolute_url()}",
                },
            ],
            "name": "Probando api",
        }
        headers = {
            "accept": "application/json",
            "Authorization": "Basic ODdiMWIyNGItYTJkNC00ZDRhLTk3YjMtNjVhODJmOWJkZjdl",
            "content-type": "application/json",
        }

        response = requests.post(url, data=json.dumps(payload), headers=headers)
        print(response.text)
        print(response.status_code)
        # super().save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'type': 'search',
                'placeholder': 'Buscar...',
                'aria-label': 'Buscar en el listado de posts',
                'class': 'form-control me-2',
            }
        ),
    )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.conf import settings
from django.db.models import Q
from .models import Post, Category
from .forms import SearchForm
from taggit.models import Tag


def post_list(request, tag_slug=None, category_id=None, category_name=None):
    object_list = Post.published.all()
    tag_list = Tag.objects.all().order_by("name")
    tag = None
    category = None
    canonical = True
    _category_name = category_name
    form_search = SearchForm()

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        canonical = False

    if category_id:
        category = get_object_or_404(Category, id=category_id)
        # todos los posts de la categoria utilizando el related_name
        object_list = category.get_posts.all()
        canonical = False

    paginator = Paginator(object_list, 10)  # posts(objects) in each page
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)  # todos los objetos de una página

    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)

    except EmptyPage:
        # if pages is out of range deliver las page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        "blog/list.html",
        {
            "category": category,
            "page": page,
            "posts": posts,
            "tag": tag,
            "tag_list": tag_list,
            "CANONICAL": canonical,
            "form": form_search,
        },
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    return render(request, "blog/detail.html", {"post": post})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # Búsqueda
            results = set(
                Post.objects.filter(
                    Q(title__icontains=query)
                    | Q(search_date__icontains=query)
                    | Q(body__icontains=query)
                    | Q(tags__name__icontains=query)
                )
            )
            print(results)

    return render(
        request,
        "blog/search.html",
        {"query": query, "form": form, "results": results},
    )

blog/templates/blog/detail.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Blog | {{ post.title }}{% endblock title %}
{% block css %}<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">{% endblock css %}
{% block csspage %}<link rel="stylesheet" href="{% static 'blog/css/blogstyle.css' %}" />{% endblock csspage %}

{% block section %}
<div class="bg-post-detail" style="background-image: radial-gradient(ellipse closest-side, rgba(0, 0, 0, 0.02), #322381),
    url('{{ post.image.url }}');">
  <div class="py-5">
    <!-- Imagen de fondo que tiene el post como cabecera -->
  </div>
</div>

<div class="b-example-divider"></div>{% endblock section %}

{% block main %}<div class="container-page-wrap mt-5">
  <!-- Breadcrumbs -->
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'blog:post-list' %}">Blog</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
    </ol>
  </nav>

  <div class="articles-and-sidebar">
    <main>
      <article class="mt-3">
        <header class="mega-header">
          <h1 class="article-title">{{ post.title }}</h1>
          <div class="author-row">
            <p>
              <img src="{% static 'blog/img/avatar.jpeg' %}" class="avatar" alt="Avatar autor">
            </p>
            <div><p class="author-name">{{ post.author }} {{ post.publish|date:"j F Y" }}</p></div>
          </div>
        </header>
        <div class="article-content bg-light shadow-lg">
          {{ post.body|safe }}
        </div>
      </article>
    </main>

    <aside class="sidebar article-detail">
      <div class="single-module">
        <div class="module">
          <a href="#">
            <img src="{% static 'blog/img/promo-1.jpg' %}" alt="imagen-patrocinador">
          </a>
        </div>
        <div class="interlude">
          <a href="#"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis voluptates.</p></a>
        </div>
      </div>
      <div class="single-module">
        <div class="module">
          <a href="#">
            <img src="{% static 'blog/img/promo-2.png' %}" alt="imagen-patrocinador">
          </a>
        </div>
        <div class="interlude">
          <a href="#"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis voluptates.</p></a>
        </div>
      </div>
    </aside>
  </div>
</div>{% endblock main %}

blog/templates/blog/latest_categories.html
<ul class="list-group list-group-flush mt-2">
  {% for category in latest_categories %}
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">
        <a href="{% url 'blog:category' category.id  category.name|slugify %}">{{ category.name }}</a>
      </div>
    </div>
    <span class="badge bg-warning rounded-pill text-dark">{{ category.get_posts.all.count }}</span>
  </li>
  {% endfor %}
</ul>

blog/templates/blog/list.html
    {% extends "core/base.html" %}
    {% load static %}

    {% block title %}Blog | Ajedrez Málaga{% endblock title %}
    {% block css %}<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">{% endblock css %}
    {% block csspage %}<link rel="stylesheet" href="{% static 'blog/css/blogstyle.css' %}" />{% endblock csspage %}

    {% block section %}
    <div class="bg-purple text-secondary px-4 py-5 text-center">
      <div class="py-5">
        <!-- left -->
        <div class="left-header-blog">
          <div>
            <img src="{% static 'blog/img/left.webp' %}" alt="">
          </div>
        </div>
        <!-- title -->
        <div class="title-header-blog">
          <img src="{% static 'blog/img/title.webp' %}" alt="Blog de Ajedrez">
        </div>
        <!-- right -->
        <div class="right-header-blog">
          <div>
            <img src="{% static 'blog/img/right.webp' %}" alt="">
          </div>
        </div>
        <!--
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <button type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Custom button</button>
          <button type="button" class="btn btn-outline-light btn-lg px-4">Secondary</button>
        </div>
        -->
      </div>
    </div>

    <div class="b-example-divider"></div>{% endblock section %}

    {% block main %}<div class="container-page-wrap mt-5">
      <!-- Breadcrumbs -->
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page">Blog</li>
        </ol>
      </nav>

      <!-- barra de búsqueda -->
      <header class="page-header col-md-6 mt-2">
        <div class="row mb-5">
          <form action="{% url 'blog:post_search' %}" method="GET" class="d-flex">
            {{ form.query }}
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>
        </div>
      </header>

      <div class="articles-and-sidebar" id="intro-posts">
        <main class="articles-wrapper">
          <!-- Articles -->
          <div class="article-grid">
            {% for post in posts %}
            <article class="article-card article anim4 intro-post">
              <div class="article-thumbnail-wrap">
                <a href="{{ post.get_absolute_url }}">
                  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="article-thumbnail">
                </a>
              </div>
              <div class="article-article">
                <header class="article-publication-meta">
                  <div class="tags">
                    {% for tag in post.tags.all %}
                      <a href="{% url 'blog:post_list_by_tag' tag.slug %}"><span>{{ tag.name }}</span></a>
                      {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </div>
                </header>
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <div class="card-content">
                  <p>{{ post.body|truncatewords_html:22|safe }}</p>
                </div>
                <div class="author-row">
                  <p>
                    <img src="{% static 'blog/img/avatar.jpeg' %}" class="avatar" alt="Avatar autor">
                  </p>
                  <div><p class="author-name">{{ post.author }} {{ post.publish|date:"j F Y" }}</p></div>
                </div>
              </div>
            </article>
            {% endfor %}
          </div>

          <!-- Pagination -->
          {% if posts %}{% include "core/pagination.html" with page=posts %}{% endif %}
        </main>

        <!-- categorías -->
        <aside class="sidebar">
          <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action bg-success text-center text-light text-uppercase" aria-current="true">
              categorías
            </button>
          </div>
          {% load blog_tags %}
          {% show_latest_categories %}
        </aside>
      </div>
    </div>{% endblock main %}

    {% block javascript %}<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/ScrollTrigger.min.js"></script>{% endblock javascript %}
    {% block extra %}<script src="{% static 'blog/js/animBlog.js' %}"></script>{% endblock extra %}

blog/templates/blog/search.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Búsqueda Artículos | Ajedrez Málaga{% endblock title %}

{% block css %}<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">{% endblock css %}

{% block csspage %}<link rel="stylesheet" href="{% static 'blog/css/blogstyle.css' %}" />{% endblock csspage %}

{% block breadcrumb %}<!-- Breadcrumb -->
<div class="container my-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'torneo:inicio' %}">Inicio</a></li>
      <li class="breadcrumb-item"><a href="{% url 'blog:post-list' %}">Blog</a></li>
      <li class="breadcrumb-item active" aria-current="page">Búsqueda</li>
    </ol>
  </nav>
</div>{% endblock breadcrumb %}

{% block section %}
<section class="container px-4 mb-5">
  <h1 class="display-5 fw-bold text-blue-gradient text-center py-5">
    Resultados de la búsqueda
  </h1>
  <div class="grid-fit">
        {% for post in results %}
        <article class="article-card article anim4 intro-post">
              <div class="article-thumbnail-wrap">
                <a href="{{ post.get_absolute_url }}">
                  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="article-thumbnail">
                </a>
              </div>
              <div class="article-article">
                <header class="article-publication-meta">
                  <div class="tags">
                    {% for tag in post.tags.all %}
                      <a href="{% url 'blog:post_list_by_tag' tag.slug %}"><span>{{ tag.name }}</span></a>
                      {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </div>
                </header>
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <div class="card-content">
                  <p>{{ post.body|truncatewords_html:22|safe }}</p>
                </div>
                <div class="author-row">
                  <p>
                    <img src="{% static 'blog/img/avatar.jpeg' %}" class="avatar" alt="Avatar autor">
                  </p>
                  <div><p class="author-name">{{ post.author }} {{ post.publish|date:"j F Y" }}</p></div>
                </div>
              </div>
            </article>
        {% empty %}
        <h3>¡Vaya!, parece que no hay resultados.</h3>
        {% endfor %}
      <!-- {% if circulares %}{% include "core/pagination.html" with page=circulares %}{% endif %} -->
  </div>  <!-- fin article grid -->
  {% if not results %}
  <div class="row mt-3">
    <!-- Búsqueda -->
    <form action="{% url 'blog:post_search' %}" method="GET" class="d-flex">
      {{ form.query }}
      <button class="btn btn-outline-success" type="submit">Buscar</button>
    </form>
  </div>
  {% endif %}
</section>{% endblock section %}