ajedrez/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
# from normativa import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path CKEDITOR
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # Path CORE
    path("", include('core.urls', namespace='torneo')),
    # Path CONTACTO
    path("contacto/", include('contacto.urls', namespace='contacto')),
    # Path NORMATIVA
    path("normativas/", include('normativa.urls', namespace='normativa')),
    # Path BLOG
    path('blog/', include('blog.urls', namespace='blog')),
    # Path CIRCUITO DIPUTACION
    path('circuito-diputacion/', include('circuitos.urls', namespace="circuitos")),
    # Path ESCUELAS Y CLUBES
    path('clubes-de-ajedrez/', include('escuelas.urls', namespace="escuelas")),
    # Path PAGE
    path("pagina/", include("page.urls", namespace="pagina")),
]

admin.site.site_header = 'Administración AjedrezMálaga'

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("search/", views.post_search, name="post_search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "categorias/<int:category_id>/<slug:category_name>/",
        views.post_list,
        name="category",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post-detail",
    ),
]

circuitos/urls.py
from django.urls import path
from . import views

app_name = 'circuitos'

urlpatterns = [
    path(
        '',
        views.circuito_torneos_list,
        {'tipo_torneo': 'nuevos'},
        name='new_tournaments',
    ),
    path("search/", views.circuito_search, name="circuito_search"),
    path(
        'todos-los-torneos/',
        views.circuito_torneos_list,
        {'all_tournaments': True, 'tipo_torneo': 'todos'},
        name='all_tournaments',
    ),
    path(
        'torneos-en-curso/',
        views.circuito_torneos_list,
        {'in_progress': True, 'tipo_torneo': 'en curso'},
        name='tournaments_in_progress',
    ),
    path(
        'torneos-finalizados/',
        views.circuito_torneos_list,
        {'finished': True, 'tipo_torneo': 'finalizados'},
        name='finished_tournaments',
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.circuito_torneo_detail,
        name='circuito-detail',
    ),
    # Path torneos año en curso
    path(
        'historico-torneos/',
        views.historico_torneos_diputacion,
        name='historico-torneos-diputacion',
    ),
    # Path torneos año y mes
    path(
        'historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos_diputacion,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos_diputacion,
        name='todo-historico',
    ),
]

contacto/urls.py
from django.urls import path
from . import views

app_name = 'contacto'

urlpatterns = [
    # Path de contacto
    path('', views.contact, name='contact'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Path del core
    path('', views.home, name="inicio"),
    path('torneos/', views.agenda, name='agenda'),
    path(
        'torneos/<int:year>/<int:month>/<int:day>/<slug:torneo>/',
        views.torneo_detail,
        name='torneo-detail',
    ),
    # Path torneos año en curso
    path('torneos/historico-torneos/', views.historico_torneos, name='historico-torneos'),
    # Path torneos año y mes
    path(
        'torneos/historico-torneos/<int:year>/<int:month>/',
        views.historico_torneos,
        name='torneos-year-month',
    ),
    # Paht todos los torneos
    path(
        'torneos/historico-torneos/<slug:all_tournaments>/',
        views.historico_torneos,
        name='todo-historico'
    ),
]

escuelas/urls.py
from django.urls import path
from . import views

app_name = 'escuelas'

urlpatterns = [
    path("", views.schools, name="schools"),
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    # Path PAGE
    path('<int:page_id>/<slug:page_title>/', views.page, name='page'),
]

core/forms.py
from django import forms
from .models import TournamentRegistration


class TournamentRegistrationForm(forms.ModelForm):
    class Meta:
        model = TournamentRegistration
        fields = [
            "name",
            "surnames",
            "mail",
            "population",
            "zip_code",
            "date_birth",
            "phone",
            "privacy_policy",
            "tournament_title",
            "status",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "surnames": forms.TextInput(attrs={"class": "form-control"}),
            "population": forms.TextInput(attrs={"class": "form-control"}),
            "zip_code": forms.TextInput(attrs={"class": "form-control"}),
            "mail": forms.EmailInput(attrs={"class": "form-control"}),
            "privacy_policy": forms.CheckboxInput(
                attrs={"class": "form-check-label", "required": True}
            ),
            "phone": forms.TextInput(
                attrs={
                    "type": "tel",
                    "required": True,
                    "pattern": "[0-9]{3}[0-9]{3}[0-9]{3}",
                    "placeholder": "666555333",
                    "class": "form-control",
                }
            ),
            "date_birth": forms.TextInput(
                attrs={
                    "type": "date",
                    "required": True,
                    "class": "form-control",
                }
            ),
        }


class LowInTournamentForm(forms.Form):
    name = forms.CharField(max_length=100)
    surnames = forms.CharField(max_length=150)
    mail = forms.EmailField()
    privacy_policy = forms.BooleanField()

    name.widget.attrs.update({"class": "form-control"})
    surnames.widget.attrs.update({"class": "form-control"})
    mail.widget.attrs.update({"class": "form-control"})
    privacy_policy.widget.attrs.update({"class": "form-check-label", "required": True})

core/views.py
import requests
import datetime
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mass_mail
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.conf import settings
from .models import Torneo, TournamentRegistration
from .forms import TournamentRegistrationForm, LowInTournamentForm


def home(request):

    return render(request, "core/home.html")


def agenda(request):
    """¿crear manager personalizados?"""

    # utilizamos date para comprobar solo fechas con el formato Y-m-d
    # Refe:https://docs.djangoproject.com/en/3.2/ref/models/querysets/#date

    torneos = Torneo.objects.all()
    torneos_nuevos = Torneo.objects.filter(
        start__date__gt=timezone.now().strftime("%Y-%m-%d")
    )
    torneos_curso = Torneo.objects.filter(
        start__date__lte=timezone.now().strftime("%Y-%m-%d"),
        finish__date__gte=timezone.now().strftime("%Y-%m-%d"),
    )
    torneos_finalizados = Torneo.objects.filter(
        finish__date__lt=timezone.now().strftime("%Y-%m-%d")
    )

    return render(
        request,
        "core/agenda.html",
        {
            "torneos": torneos,
            "torneos_nuevos": torneos_nuevos,
            "torneos_curso": torneos_curso,
            "torneos_finalizados": torneos_finalizados,
        },
    )


def torneo_detail(request, year, month, day, torneo):
    torneo = get_object_or_404(
        Torneo, slug=torneo, publish__year=year, publish__month=month, publish__day=day
    )
    allow_registration = False
    submitted_form = False

    if not torneo.quantity and not torneo.registre:  # organiza delegación y no aforo
        allow_registration = False
    elif timezone.now().strftime("%Y-%m-%d") >= torneo.end_registration.strftime(
        "%Y-%m-%d"
    ):  # para todos organize quien organize
        allow_registration = False
    elif torneo.quantity and not torneo.registre:  # organiza delegación y hay aforo
        allow_registration = True
    elif not torneo.quantity and torneo.registre:
        # organiza 3 parte y fecha actual < fecha fin registro
        allow_registration = True

    form = TournamentRegistrationForm()
    low_form = LowInTournamentForm()

    if request.method == "POST":
        if "low" in request.POST:
            low_form = LowInTournamentForm(request.POST)
            form = TournamentRegistrationForm()

            if low_form.is_valid():
                """reCAPTCHA validation"""
                recaptcha_response = request.POST.get("g-recaptcha-response")
                data = {
                    "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                    "response": recaptcha_response,
                }
                r = requests.post(
                    "https://www.google.com/recaptcha/api/siteverify", data=data
                )
                result = r.json()

                print(result)

                """ if reCAPTCHA returns True """
                if result["success"]:
                    # diccionario datos limpios del formulario de baja
                    cd = low_form.cleaned_data
                    try:
                        registration = TournamentRegistration.objects.get(
                            name=cd["name"],
                            surnames=cd["surnames"],
                            mail=cd["mail"],
                            tournament_title=request.POST.get("tournament_title"),
                        )
                        registration.delete()
                        messages.info(request, "Baja realizada con éxito.")
                        torneo.quantity = torneo.quantity + 1  # update
                        torneo.save()
                        message1 = (
                            "Baja en torneo",
                            f"Enhorabuena {cd['name']} te has dado de baja en el torneo {torneo.title}",
                            "info@ajedrezmalaga.org",
                            [f"{cd['mail']}"],
                        )
                        message2 = (
                            "Baja en torneo",
                            f"{cd['name']} {cd['surnames']} se ha dado de baja en el torneo {torneo.title}",
                            "info@ajedrezmalaga.org",
                            ["admin@ajedrezmalaga.org"],
                        )

                        send_mass_mail((message1, message2), fail_silently=False)
                        low_form = LowInTournamentForm()
                    except ObjectDoesNotExist:
                        messages.error(request, "El usuario no está registrado.")

        elif not "low" in request.POST:
            form = TournamentRegistrationForm(request.POST)
            low_form = LowInTournamentForm()

            if form.is_valid():
                """reCAPTCHA validation"""
                recaptcha_response = request.POST.get("g-recaptcha-response")
                data = {
                    "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                    "response": recaptcha_response,
                }
                r = requests.post(
                    "https://www.google.com/recaptcha/api/siteverify", data=data
                )
                result = r.json()

                print(result)

                """ if reCAPTCHA returns True """
                if result["success"]:
                    print("FORMULARIO ENVIADO CON EXITO")
                    new_tournamentregistration = form.save(commit=False)
                    new_tournamentregistration.tournament = torneo
                    # new_tournamentregistration.status = request.POST.get('status')
                    new_tournamentregistration.save()

                    torneo.quantity = torneo.quantity - 1  # update
                    torneo.save()
                    # print('Torneo despues de grabar', torneo.quantity)

                    # envio correo electronico a la delegación y al registrado
                    # para ello utilizaremos send_mass_mail()
                    # https://docs.djangoproject.com/en/3.2/topics/email/#send-mass-mail
                    cd = form.cleaned_data

                    message1 = (
                        "Inscripción en torneo",
                        f"Enhorabuena {cd['name']} te has registrado en el torneo {torneo.title}",
                        "info@ajedrezmalaga.org",
                        [f"{cd['mail']}"],
                    )
                    message2 = (
                        "Inscripción en torneo",
                        f"{cd['name']} {cd['surnames']} se ha registrado en el torneo {torneo.title}",
                        "info@ajedrezmalaga.org",
                        ["admin@ajedrezmalaga.org"],
                    )

                    send_mass_mail((message1, message2), fail_silently=False)

                    submitted_form = True
                    form = TournamentRegistrationForm()  # borrar campos crear form nuevo

    # else:
    #     form = TournamentRegistrationForm()
    #     low_form = LowInTournamentForm()

    return render(
        request,
        "core/torneo-detail.html",
        {
            "torneo": torneo,
            "allow_registration": allow_registration,
            "recaptcha_site_key": settings.GOOGLE_RECAPTCHA_SITE_KEY,
            "form": form,
            "submitted_form": submitted_form,
            "low_form": low_form,
        },
    )


def historico_torneos(request, year=None, month=None, all_tournaments=None):
    '''Vamos a obtener los torneos de los dos años anteriores al año en curso, los
    torneos del año en curso y los torneos de un año y un mes'''

    year_month_tournaments = None
    get_all_tournaments = False
    qs = False
    formatted_date = ''
    before_last_year = str(int(timezone.now().strftime("%Y")) - 2)
    last_year = str(int(timezone.now().strftime("%Y")) - 1)
    current_year = timezone.now().strftime("%Y")
    # current_month = timezone.now().strftime("%m")

    if all_tournaments:
        get_all_tournaments = Torneo.objects.all()

    if year and month:
        year_month_tournaments = Torneo.objects.filter(
            start__year=int(year), start__month=int(month)
        )
        qs = True
        formatted_date = datetime.datetime(year, month, 17).strftime("%B %Y")
        print(formatted_date)

    # todos los torneos cuya fecha de comienzo es el mes actual del año curso
    # current_month_tournaments = Torneo.objects.filter(start__month=current_month)
    current_year_tournaments = Torneo.objects.filter(start__year=current_year)

    return render(
        request,
        "core/historico-torneos.html",
        {
            "current_year_tournaments": current_year_tournaments,
            'current_year': current_year,
            'last_year': last_year,
            'before_last_year': before_last_year,
            'year_month_tournaments': year_month_tournaments,
            'qs': qs,
            'formatted_date': formatted_date,
            'get_all_tournaments': get_all_tournaments
        },
    )


# def todo_historico(request):
#     all_tournaments = Torneo.objects.all()

#     return render(
#         request, 'core/historico-torneos.html', {'all_tournaments': all_tournaments}
#     )

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <link href="https://fonts.googleapis.com/css?family=Poppins:400,700,800,900&display=swap" rel="stylesheet"> -->
    <!-- Favicon -->
    <link rel="icon" href="/static/core/img/logo.webp" />
    <title>{% block title %}{% endblock title %}</title>

    <!-- estilos -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="{% static 'core/css/main.css' %}" />
    {% block csspage %}{% endblock csspage %}

    <!-- Google recaptcha -->
    {% block recaptcha %}{% endblock recaptcha %}

    <!-- OneSignal -->
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
      window.OneSignal = window.OneSignal || [];
      // Rest Api Key: ODdiMWIyNGItYTJkNC00ZDRhLTk3YjMtNjVhODJmOWJkZjdl
      OneSignal.push(function () {
        OneSignal.SERVICE_WORKER_PARAM = { scope: '/static/core/js/onesignal/' };
        OneSignal.SERVICE_WORKER_PATH = '/static/core/js/onesignal/OneSignalSDKWorker.js'
        OneSignal.init({
          appId: "a916b202-a622-4aa2-8556-b4dcf3bc60ef",
          allowLocalhostAsSecureOrigin: true,
        });
      });
    </script>
  </head>

  <body>
    {% block grecaptcha %}{% endblock grecaptcha %}
    <!-- Back to Top -->
    <a id="back2Top" title="Ir Arriba" href="#">
      <svg width="32" height="32" viewBox="0 0 100 100">
        <path
          fill="white"
          d="m50 0c-13.262 0-25.98 5.2695-35.355 14.645s-14.645 22.094-14.645 35.355 5.2695 25.98 14.645 35.355 22.094 14.645 35.355 14.645 25.98-5.2695 35.355-14.645 14.645-22.094 14.645-35.355-5.2695-25.98-14.645-35.355-22.094-14.645-35.355-14.645zm20.832 62.5-20.832-22.457-20.625 22.457c-1.207 0.74219-2.7656 0.57812-3.7891-0.39844-1.0273-0.98047-1.2695-2.5273-0.58594-3.7695l22.918-25c0.60156-0.61328 1.4297-0.96094 2.2891-0.96094 0.86328 0 1.6914 0.34766 2.293 0.96094l22.918 25c0.88672 1.2891 0.6875 3.0352-0.47266 4.0898-1.1562 1.0508-2.9141 1.0859-4.1133 0.078125z"
        ></path>
      </svg>
    </a>

    <header class="sticky-top shadow-sm">
      <!-- Menú navegación -->
      <nav class="navbar navbar-expand-xl navbar-light bg-light">
        <div class="container-fluid gap">
          <a class="navbar-brand" href="{% url 'torneo:inicio' %}"></a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'torneo:inicio' %}"><i class="bi bi-house"></i> Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path|slice:":6" == '/blog/' %}active{% endif %}" href="{% url 'blog:post-list' %}"><i class="bi bi-newspaper"></i> Blog</a>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle {% if request.path|slice:":9" == '/torneos/' %}active{% endif %}"
                  aria-current="page"
                  href="{% url 'torneo:agenda' %}"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="bi bi-trophy"></i> Torneos
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item {% if request.path|slice:"10:" == '' %}active{% endif %}" href="{% url 'torneo:agenda' %}" aria-current="true">
                      <i class="bi bi-journals"></i> Agenda ajedrez Málaga
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item {% if request.path|slice:":27" == '/torneos/historico-torneos/' %}active{% endif %}" href="{% url 'torneo:historico-torneos' %}"><i class="bi bi-list-columns"></i> Histórico torneos</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path|slice:":12" == '/normativas/' %}active{% endif %}" href="{% url 'normativa:circulares' %}" tabindex="-1" aria-disabled="true"
                  ><i class="bi bi-arrow-clockwise"></i> Normativas</a
                >
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if request.path|slice:":21" == '/circuito-diputacion/' %}active{% endif %}"
                  aria-current="page"
                  href="{% url 'circuitos:new_tournaments' %}"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                  >
                  <i class="bi bi-diagram-2"></i> Circuito Diputación
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item {% if tipo_torneo %}active{% endif %}" href="{% url 'circuitos:new_tournaments' %}" aria-current="true">
                      <i class="bi bi-journals"></i> Agenda Diputación
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item {% if request.path|slice:":39" == '/circuito-diputacion/historico-torneos/' %}active{% endif %}" href="{% url 'circuitos:historico-torneos-diputacion' %}"><i class="bi bi-list-columns"></i> Histórico Circuitos Diputación</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"><i class="bi bi-save"></i> Repositorio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path|slice:":19" == '/clubes-de-ajedrez/' %}active{% endif %}" href="{% url 'escuelas:schools' %}"><i class="bi bi-shop"></i> Clubes</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% if request.path|slice:":10" == '/contacto/' %}active{% endif %}" href="{% url 'contacto:contact' %}"><i class="bi bi-envelope"></i> Contacto</a>
              </li>
            </ul>
            <!--
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" />
              <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            -->
          </div>
        </div>
      </nav>
    </header>

    {% block carrusel %}{% endblock carrusel %}

    {% block breadcrumb %}{% endblock breadcrumb %}
    {% block section %}{% endblock section %}

    {% block main %}{% endblock main %}

    {% block extrasection %}{% endblock extrasection %}

    <footer class="bd-footer py-4 py-md-5 mt-5 bg-light">
      <div class="container py-4 py-md-5 px-4">
        <div class="row">
          <div class="col-lg-4 mb-5">
            <p class="fs-5 mb-1 text-purple">Subscríbete a nuestra Newsletter</p>
            <div class="newsletter-subscribe">
              <div class="intro">
                <p>Mantente informado sobre ajedrez Málaga.</p>
              </div>
              <form class="d-flex">
                <input class="form-control" type="email" name="email" placeholder="@Email">
                <button class="btn btn-primary" type="button">Enviar</button>
              </form>
            </div>
          </div>
          <div class="col-6 col-lg-2 offset-lg-1 mb-3">
            <h5 class="text-purple">Site map</h5>
            <ul class="list-unstyled">
              <li class="mb-2"><a href="#">Inicio</a></li>
              <li class="mb-2"><a href="#">Blog</a></li>
              <li class="mb-2"><a href="#">Torneos</a></li>
              <li class="mb-2"><a href="#">Histórico torneos</a></li>
              <li class="mb-2"><a href="#">Normativas</a></li>
              <li class="mb-2"><a href="#">Circuito Diputación</a></li>
              <li class="mb-2"><a href="#">Repositorio</a></li>
              <li class="mb-2"><a href="#">Contacto</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2 mb-3">
            <h5 class="text-purple">Páginas</h5>
            <ul class="list-unstyled">
              {% load pages_extras %}
              {% get_page_list as page_list %}

              {% for page in page_list %}
              <li class="mb-2">
                <a href="{% url 'pagina:page' page.id page.title|slugify %}" rel="nofollow">{{ page.title }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="col-6 col-lg-3 mb-3">
            <h5 class="text-purple">Redes Sociales</h5>
            <p><i class="bi bi-geo-alt"></i> C/ San Juan, 25</p>
            <p><i class="bi bi-telephone"></i> 952 67 89 07</p>
            <p><i class="bi bi-envelope"></i> info@example.com</p>
            <ul class="list-unstyled d-flex redes-sociales">
              <li class="me-4">
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
</svg>
                </a>
              </li>
              <li class="me-4">
                <a href="#"><i class="bi bi-instagram"></i></a>
              </li>
              <li class="me-4">
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- JavaScript -->
    <script type="text/javascript" src="{% static 'core/js/jquery-3.6.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/scroll-up.js' %}"></script>
    {% block javascript %}{% endblock javascript %}

    {% block extra %}{% endblock extra %}
  </body>
</html>

core/templates/core/pagination.html
<!-- Pagination -->
<nav class="my-4" aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
    </li>
  {% endif %}  
    
  {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}

  {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Siguiente</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Siguiente</a>
    </li>
  {% endif %}
  </ul>
</nav>